### PR TITLE
fixed pipe escaping in tables

### LINKED ISSUE #139: Escaping pipe symbol
I've got a problem with rendered text from annotation `@Pattern`.
A pipe symbol (|) within a regular expression breaks a table.

Spring Auto REST Docs is creation the following snippet:
```
|===
|Path|Type|Optional|Description

|id
|Integer
|true
|Item ID. +
javax.validation.constraints.NotBlank.

|description
|String
|true
|Item description. +
Size must be between 0 and 20 inclusive.

|patternString
|String
|true
|This is a regex pattern. +
Must match the regular expression `(TEST)|(LIVE)`.

|===
```
When HTML-documemnt is created by asciidoc (LIVE) is omitted. Also text isn't rendered in monospace. If one escapes the pipe (`(TEST)\|(LIVE)` you get the right result.
Can you add escaping of pipe symbols within regular expessions?
I've added a [sample project](https://github.com/rgmonk/playground/tree/master/rest-auto-doc-demo).

### PR DESCRIPTION
**Pull request by jmisur**
fixes #139

### CODE REVIEW

File: spring-auto-restdocs-core/src/test/java/capital/scalable/restdocs/payload/JacksonResponseFieldSnippetTest.java [hunk 1]
```diff
@@ -230,7 +230,23 @@ public void failOnUndocumentedFields() throws Exception {
...
+
+        new JacksonResponseFieldSnippet().responseBodyAsType(ProcessingResponse.class)
+                .document(operationBuilder
+                        .attribute(HandlerMethod.class.getName(), handlerMethod)
+                        .attribute(ObjectMapper.class.getName(), mapper)
+                        .attribute(JavadocReader.class.getName(), javadocReader)
+                        .attribute(ConstraintReader.class.getName(), constraintReader)
+                        .build());
+    }
     private void mockConstraintMessage(Class<?> type, String fieldName, String comment) {
```
Comment (fbenz) [inline spring-auto-restdocs-core/src/test/java/capital/scalable/restdocs/payload/JacksonResponseFieldSnippetTest.java]: empty line missing above ;)

File: spring-auto-restdocs-core/src/main/java/capital/scalable/restdocs/snippet/StandardTableSnippet.java [hunk 2]
```diff
@@ -140,7 +140,7 @@ private String joinAndFormat(String description, List<String> constraints,
 
         res.append(constr.toString());
 
-        return res.toString();
+        return res.toString().replace("|", "\\|");
```
Comment (fbenz) [inline spring-auto-restdocs-core/src/main/java/capital/scalable/restdocs/snippet/StandardTableSnippet.java]: General questions is on which characters to escape, e.g. * _ &. We never had an issue so far and thus I think that it's fine to not add them for now.

Comment (jmisur) [reply spring-auto-restdocs-core/src/main/java/capital/scalable/restdocs/snippet/StandardTableSnippet.java]: this one is important only in tables. Of course more generic escaping would be beneficial
