### PR TITLE
Fix mixing modelattribute with other annotations

### LINKED ISSUE #426: Documenting RequestParam DTOs
Because we have too many request parameter for some endpoints we decided to wrap them into dedicated DTO like so:

``` 
@GetMapping(path = "/url")
@Transactional(readOnly = true, rollbackFor = Exception.class)
public ResponseEntity<?> getListOfSomething(
  FilterParameter filterParameter,
  SortParameter sortParameter,
  PagingParameter pagingParameter) { 
    /*...*/
}
```
Unfortunately this way the code looks clean, but the request parameters which are contained within each DTO is not documented.

Is this currently not supported or are we doing something wrong?

### PR DESCRIPTION
**Pull request by jmisur**
Fixes #426 for good.

[Other types without annotation](https://docs.spring.io/spring-framework/docs/current/reference/html/web.html#mvc-ann-arguments) handled by other method argument resolvers are not considered when handling model attribute with or without annotation.

Notice the disappearing of `Pageable` fields from documentation.

### CODE REVIEW

File: spring-auto-restdocs-core/src/main/java/capital/scalable/restdocs/payload/JacksonModelAttributeSnippet.java [hunk 1]
```diff
@@ -62,16 +60,18 @@ public JacksonModelAttributeSnippet(Collection<HandlerMethodArgumentResolver> ha
...
                 .toArray(Type[]::new);
     }
 
-    private boolean isModelAttribute(MethodParameter param) {
-        return param.getParameterAnnotation(ModelAttribute.class) != null
-                || param.getParameterAnnotations().length == 0 && !BeanUtils.isSimpleProperty(param.getParameterType());
-    }
-
+    /**
+     * Iterates over list of method argument resolvers and returns the first the same way as in
```
Comment (fbenz) [inline spring-auto-restdocs-core/src/main/java/capital/scalable/restdocs/payload/JacksonModelAttributeSnippet.java:69]:
```suggestion
     * Iterates over a list of method argument resolvers and returns the first in the same way as in
```

**Review by fbenz — APPROVED** [review]
Thanks
