### PR TITLE
Handling missing generics in response entity

### LINKED ISSUE #144: ResponseEntity without generics throws ClassCastException

### PR DESCRIPTION
**Pull request by jmisur**
fixes #144

### CODE REVIEW

File: spring-auto-restdocs-core/src/test/java/capital/scalable/restdocs/payload/JacksonResponseFieldSnippetTest.java [hunk 1]
```diff
@@ -178,6 +178,20 @@ public void responseEntityResponse() throws Exception {
     }
 
     @Test
+    public void responseEntityResponseWithoutGenerics() throws Exception {
+        HandlerMethod handlerMethod = createHandlerMethod("responseEntityItem2");
+
+        this.snippets.expect(RESPONSE_FIELDS).withContents(equalTo("No response body."));
```
Comment (fbenz) [inline spring-auto-restdocs-core/src/test/java/capital/scalable/restdocs/payload/JacksonResponseFieldSnippetTest.java]: `Unknown response body.` would be more accurate, but that is a different story.
